Eval:
    gt_root: "dataset/TestDataset"
    pred_root: "model_pth/PolypFormer/PolypFormer.pth"
    result_path: "results_map"
    datasets: ['CVC-300', 'CVC-ClinicDB', 'Kvasir', 'CVC-ColonDB', 'ETIS-LaribPolypDB']
#    datasets: ['CVC-300', 'CVC-ClinicDB', 'CVC-ColonDB', 'ETIS-LaribPolypDB']
    metrics: ['meanDic', 'meanIoU']
#    , 'wFm', 'Sm', 'meanEm', 'mae', 'maxEm', 'maxDic', 'maxIoU', 'meanSen', 'maxSen', 'meanSpe', 'maxSpe']